[theme]
base = "dark"
primaryColor = "#FF7A45"
backgroundColor = "#0A0A0C"
secondaryBackgroundColor = "#1C1C22"
textColor = "#FFFFFF"

[theme.sidebar]
backgroundColor = "#141418"
secondaryBackgroundColor = "#24242C"
textColor = "#FFFFFF"

[server]
headless = true
